### ISSUE TITLE
08_パスワード入力ページ  (=> 詳細ページ遷移用)

### ISSUE THREAD

**Issue by fukuidaito** [wahei628/ShareSuke#12]
- [x] gem BCryptの調査
- [x] gem BCryptの導入 (必要に応じてマイグレーション修正)
- [x] イベント作成時にパスワードがハッシュ化されるように実装
- [x] passwor → password_hashにカラム名を変更

- [x] ルーティングの追加 (entry_password)
- [x] パスワード入力画面の作成
- [x] パスワードが設定されている場合、eventsコントローラーのshowにレンダリング先の分岐を追加
- [x] URLシェア画面からパスワードの表示を削除
- [x] イベント作成画面でパスワードがコピーできるように追加

**Comment by Dingu-suke** [comment]
イベント作成ページから詳細ページに飛ぶ前のパスワードを入力するワンクッション。
イベント作成ページ => イベント詳細ページ という遷移になっているので、このページの作成が完了次第、
遷移パスをこのページに変更する。

**Comment by Dingu-suke** [comment]
Basic認証でも。
