### ISSUE TITLE
07_イベント作成ページ ( => イベント詳細ページ )

### ISSUE THREAD

**Issue by fukuidaito** [wahei628/ShareSuke#3]

**Comment by Dingu-suke** [comment]
URL  : event/new

フォーム
| 実装内容 | バリデーション | 備考 |
| ---- | ---- |----| 
| イベント名 | `presence true` |  |
| 候補日程 | `1つ以上` | カレンダーから反映させたい(後からでもok) |
| イベント説明文 |  |  | 
| メールアドレス | @とか | DBにカラム未追加。後からでもok |
| パスワード |  |  |
